name: crossloc

channels:
- anaconda
- pytorch
- conda-forge

dependencies:
  - python=3.7
  - pip
  - opencv=3.4.2
  - pip:
    - torch==1.9.0
    - torchvision==0.10.0
    - numpy
    - matplotlib
    - cython
    - scikit-image==0.16.2
    - scipy
    - scikit-learn
    - tqdm
    - gitpython
    - kornia
    - pyproj
    - jupyterlab
    - open3d==0.9.0
    - visualpriors
    - transforms3d
